// E-board members — swap initials for portrait image paths in /public/img/ when ready
export const MEMBERS = [
    { id: 1, name: "Amara Whitfield", role: "President", roman: "I", category: "executive", initials: "AW", major: "Political Science", class: "'26", hometown: "Charlotte, NC", since: "2024", bio: "Steers the chapter strategy, chairs general body meetings, and represents the Project at the Inter-Org Council. Two-time recipient of the Aggie Service Medallion." },
    { id: 2, name: "Marcus Beaumont", role: "Vice President", roman: "II", category: "executive", initials: "MB", major: "Architecture", class: "'26", hometown: "Greensboro, NC", since: "2024", bio: "Runs operations and stands in for the President. Founded the Mural Guild and still spends Saturday mornings on the scaffold." },
    { id: 3, name: "Imani Carter-Boyd", role: "Treasurer", roman: "III", category: "executive", initials: "IC", major: "Accounting", class: "'27", hometown: "Raleigh, NC", since: "2025", bio: "Keeps the books, files for grants, and runs the chapter's spring fundraising drive. Has not let a receipt go unreconciled in 18 months." },
    { id: 4, name: "Dorian Ellis", role: "Secretary", roman: "IV", category: "executive", initials: "DE", major: "English", class: "'27", hometown: "Durham, NC", since: "2025", bio: "Keeper of minutes and our institutional memory. Edits the quarterly chapter newsletter, 'The Codex.'" },
    { id: 5, name: "Naomi Sanders", role: "Director of Programs", roman: "V", category: "programs", initials: "NS", major: "Sociology", class: "'26", hometown: "Atlanta, GA", since: "2024", bio: "Designs the semesterly project calendar. Liaises with McNair Elementary and the Hayes-Taylor YMCA on tutoring placements." },
    { id: 6, name: "Cameron Yates", role: "Events Coordinator", roman: "VI", category: "programs", initials: "CY", major: "Business Admin", class: "'27", hometown: "Newark, NJ", since: "2025", bio: "Plans the spring festival, formal, and four signature service days. Logistics specialist, vibe specialist." },
    { id: 7, name: "Aaliyah Trent", role: "Service Chair", roman: "VII", category: "programs", initials: "AT", major: "Social Work", class: "'27", hometown: "Fayetteville, NC", since: "2025", bio: "Coordinates weekly volunteer rosters and stand-ups. Built the chapter's volunteer-hour tracking system from scratch." },
    { id: 8, name: "Devin Marshall", role: "Tutoring Lead", roman: "VIII", category: "programs", initials: "DM", major: "Elementary Education", class: "'26", hometown: "Charlotte, NC", since: "2024", bio: "Runs the McNair afterschool program and trains new tutors. Won the 2025 Aggie Mentor of the Year award." },
    { id: 9, name: "Jasmine Okafor", role: "Salon Chair", roman: "IX", category: "programs", initials: "JO", major: "African American Studies", class: "'26", hometown: "Lagos, Nigeria", since: "2024", bio: "Curates the Thursday salon reading list and moderates discussions. Co-founded the joint salon series with Bennett College." },
    { id: 10, name: "Khadijah Owens", role: "Creative Director", roman: "X", category: "creative", initials: "KO", major: "Visual Arts", class: "'26", hometown: "Wilmington, NC", since: "2024", bio: "Designs the chapter's print and digital identity. Curates the Salon & Study reading list with the faculty advisor." },
    { id: 11, name: "Trey Hollister", role: "Media Lead", roman: "XI", category: "creative", initials: "TH", major: "Journalism", class: "'27", hometown: "Memphis, TN", since: "2025", bio: "Shot, edited, and scored the chapter trailer. Runs the documentary team and the @rp_ncat instagram." },
    { id: 12, name: "Solomon Reyes", role: "Mural Guild Lead", roman: "XII", category: "creative", initials: "SR", major: "Painting & Drawing", class: "'26", hometown: "San Juan, PR", since: "2024", bio: "Heads the Mural Guild — handles wall selection, sketch reviews, and partnerships with city Parks. Up on the scaffold every Saturday." },
    { id: 13, name: "Aria Bennett", role: "Editor, The Codex", roman: "XIII", category: "creative", initials: "AB", major: "Creative Writing", class: "'27", hometown: "Brooklyn, NY", since: "2025", bio: "Edits 'The Codex,' our quarterly zine. Solicits writing from members, alumni, and faculty across the Triad." },
    { id: 14, name: "Malik Henderson", role: "Photography Lead", roman: "XIV", category: "creative", initials: "MH", major: "Visual Communications", class: "'27", hometown: "Houston, TX", since: "2025", bio: "Documents every chapter event. Built the photo archive and trains the new photo team each fall." },
    { id: 15, name: "Jeremiah Vance", role: "Director of Outreach", roman: "XV", category: "outreach", initials: "JV", major: "Marketing", class: "'27", hometown: "Washington, DC", since: "2025", bio: "Owns the relationship with our 26 partner orgs. Negotiated the Sunday open-air rights for the Stewart Block." },
    { id: 16, name: "Sade Brockington", role: "Membership Chair", roman: "XVI", category: "outreach", initials: "SB", major: "Public Health", class: "'27", hometown: "Columbia, SC", since: "2025", bio: "Recruits the new cohort each fall and shepherds applicants through the intake process. Hosts open houses at the AHC." },
    { id: 17, name: "Tobias Greene", role: "Community Liaison", roman: "XVII", category: "outreach", initials: "TG", major: "Urban & Regional Planning", class: "'26", hometown: "East Greensboro, NC", since: "2024", bio: "The chapter's bridge to East Greensboro residents and small businesses. Grew up two blocks from our mural sites." },
    { id: 18, name: "Lauren Pierce", role: "Partnerships Chair", roman: "XVIII", category: "outreach", initials: "LP", major: "Communications", class: "'26", hometown: "Hampton, VA", since: "2024", bio: "Cultivates corporate and academic partnerships. Closed the chapter's first multi-year sponsorship in fall 2025." },
    { id: 19, name: "Nia Sutherland", role: "PR & Comms", roman: "XIX", category: "outreach", initials: "NS", major: "Strategic Communications", class: "'27", hometown: "Tallahassee, FL", since: "2025", bio: "Press releases, partner emails, the chapter newsletter masthead. Voice of the Renaissance Project online and off." },
  ];

export const MEMBER_FILTERS = [
  { id: "all", label: "All · 19" },
  { id: "executive", label: "Executive" },
  { id: "programs", label: "Programs" },
  { id: "creative", label: "Creative" },
  { id: "outreach", label: "Outreach" },
];
